### ISSUE TITLE
Got duplicate entry (didn't check if any other)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-usage-dashboard#37]
https://github.com/datalad/datalad-usage-dashboard/blob/5191f339b55e50db16bab17f9b08a24da1b6afe5/READMEs/cryo-data.md
has

1	[cryo-data/cryo-data](https://github.com/cryo-data/cryo-data)	1	✔️		
2	[cryo-data/cryo-data](https://github.com/cryo-data/cryo-data)	1	✔️

which shouldn't happen AFAIK

**Comment by jwodder** [comment]
@yarikoptic That repository is listed twice in `datalad-repos.json` with two different IDs.  I'm guessing that the repository was created, the script found it, the repository was deleted & recreated between runs of the script, and then the script found the new repository, but the old one wasn't marked as "gone" because a repository with the given name existed.

**Comment by yarikoptic** [comment]
Thanks for the analysis!  I think we should just then let RiP (delete record, not to move into Gone) those (IDs) for which there is a new (larger ID?) repo under that name.
